
found 0 vulnerabilities
MongoDB connection error: MongoServerSelectionError: C02D09C1AD7F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:916:SSL alert number 80

    at Topology.selectServer (/home/runner/workspace/server/node_modules/mongodb/lib/sdam/topology.js:326:38)
    at async Topology._connect (/home/runner/workspace/server/node_modules/mongodb/lib/sdam/topology.js:200:28)
    at async Topology.connect (/home/runner/workspace/server/node_modules/mongodb/lib/sdam/topology.js:152:13)
    at async topologyConnect (/home/runner/workspace/server/node_modules/mongodb/lib/mongo_client.js:258:17)
    at async MongoClient._connect (/home/runner/workspace/server/node_modules/mongodb/lib/mongo_client.js:271:13)
    at async MongoClient.connect (/home/runner/workspace/server/node_modules/mongodb/lib/mongo_client.js:196:13)
    at async connectDB (file:///home/runner/workspace/server/index.js:21:5)
    at async startServer (file:///home/runner/workspace/server/index.js:110:3) {
  errorLabelSet: Set(0) {},
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'ac-fvqewuk-shard-00-02.1zomfpq.mongodb.net:27017' => [ServerDescription],
      'ac-fvqewuk-shard-00-00.1zomfpq.mongodb.net:27017' => [ServerDescription],
      'ac-fvqewuk-shard-00-01.1zomfpq.mongodb.net:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-iijk93-shard-0',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  [cause]: MongoNetworkError: C02D09C1AD7F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:916:SSL alert number 80
  
      at TLSSocket.<anonymous> (/home/runner/workspace/server/node_modules/mongodb/lib/cmap/connect.js:286:44)
      at Object.onceWrapper (node:events:639:26)
      at TLSSocket.emit (node:events:524:28)
      at emitErrorNT (node:internal/streams/destroy:169:8)
      at emitErrorCloseNT (node:internal/streams/destroy:128:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    errorLabelSet: Set(1) { 'ResetPool' },
    beforeHandshake: false,
    [cause]: [Error: C02D09C1AD7F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:916:SSL alert number 80
    ] {
      library: 'SSL routines',
      reason: 'tlsv1 alert internal error',
      code: 'ERR_SSL_TLSV1_ALERT_INTERNAL_ERROR'
    }
  }
}
Continuing without database connection...
Server running on http://0.0.0.0:3001